### ISSUE TITLE
Found an "Unknown" colour that affects the parry

### ISSUE THREAD

**Issue by LuceScarlet** [BrandenEK/Blasphemous-Skin-Editor#2]
When I started to create skins last year I found an issue with parries. When TPO blocked an attack, they were black and it's kind of cool, but it wasn't white as the game skins.
Left is the original block and the right one is the skin created with the skin editor
![image](https://github.com/BrandenEK/Blasphemous-Custom-Skins/assets/129603784/13b37f35-6c00-48d2-9a93-fb08307cb85d)

After testing and messing around with those "Unkown" colours, I found that the very first square from "Unknown" part was related to that and changing it to white, the parry was corrected; or if other colour is used, it's part of the skin (obviously, I've changed to magenta to show it xD)
![image](https://github.com/BrandenEK/Blasphemous.Modding.SkinEditor/assets/129603784/40831686-4c69-4a77-ad0c-41cbcd71887e)
![image](https://github.com/BrandenEK/Blasphemous-Custom-Skins/assets/129603784/7b4290b6-32dc-4803-b907-9b79b19690c6)

Maybe add that square to "White" should be great to avoid that confussion?
Also, I think the colour should be #FFFFFF by default instead of #000000 as the default skin has this issue too if it's exported without editing it.

**Comment by BrandenEK** [comment]
Yep, that black section on the parry animation has been bothering me for a while.  I couldnt figure out what was causing it, as any skin exported had it, even the original default skin

**Comment by BrandenEK** [comment]
Unfortunately, its not as easy as just changing the default for that pixel, since the colors first displayed on the buttons are loaded from the default skin.  So for some reason the editor thinks that the pixel is black on the default skin

**Comment by BrandenEK** [comment]
Actually, if you look at the default skin here (https://github.com/BrandenEK/Blasphemous.Modding.SkinEditor/blob/main/Original%20skins/PENITENT_DEFAULT.png), the first pixel in the texture (Which is responsible for that part of the parry) is black for some reason.  I think this would be solved if that pixel was moved into an actual group instead of 'Unknown' and was represented on a preview image or was forced to be default white

**Comment by BrandenEK** [comment]
I would like to update this editor eventually with the following features:
- Rescalable window
- All pixels determined
- Fixed parry color
- Support for custom blas2 skins

Hopefully we can get some of these features implemented before a blas2 update with different skins

**Comment by BrandenEK** [comment]
v2.0.0 fixes this issue
